CREATE TABLE "chatbot"."erp_columns" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_key" text NOT NULL,
	"name" text NOT NULL,
	"label" text NOT NULL,
	"type" text NOT NULL,
	"pk" boolean DEFAULT false NOT NULL,
	"searchable" boolean DEFAULT false NOT NULL,
	"filterable" boolean DEFAULT false NOT NULL,
	"sortable" boolean DEFAULT false NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "erp_columns_table_key_name_unique" UNIQUE("table_key","name")
);
--> statement-breakpoint
CREATE TABLE "chatbot"."erp_tables" (
	"key" text PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"synonyms" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"joins" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"notes" text,
	"position" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chatbot"."erp_columns" ADD CONSTRAINT "erp_columns_table_key_erp_tables_key_fk" FOREIGN KEY ("table_key") REFERENCES "chatbot"."erp_tables"("key") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "erp_columns_table_key_idx" ON "chatbot"."erp_columns" USING btree ("table_key");
--> statement-breakpoint
-- Seed the ERP tables model from DEFAULT_ERP_MODEL (lib/erp-schema/model.ts), so
-- the seed and the runtime fallback are identical. Without a seed the app already
-- falls back to the same content; seeding makes it editable from the admin
-- "Schemat bazy" screen.
INSERT INTO "chatbot"."erp_tables" ("key", "label", "description", "synonyms", "joins", "notes", "position") VALUES
	('kontrahenci', 'Kontrahenci', 'Klienci i dostawcy — dane rejestrowe.', '["klient","kontrahent","dostawca","firma"]'::jsonb, '[]'::jsonb, NULL, 0),
	('towary', 'Towary', 'Produkty i stany magazynowe.', '["towar","produkt","asortyment","materiał","stan magazynowy (= ilosc_dostepna)"]'::jsonb, '[]'::jsonb, NULL, 1),
	('faktury_sprzedazy', 'Faktury sprzedaży', 'Dokumenty sprzedaży i statusy.', '["faktura","FA","sprzedaż"]'::jsonb, '["kontrahent_kod -> kontrahenci.kod"]'::jsonb, NULL, 2),
	('faktury_sprzedazy_pozycje', 'Pozycje faktur sprzedaży', 'Pozycje dokumentów sprzedaży.', '[]'::jsonb, '["numer_faktury -> faktury_sprzedazy.numer_dokumentu","towar_kod -> towary.kod"]'::jsonb, NULL, 3),
	('faktury_zakupu', 'Faktury zakupu', 'Dokumenty zakupu od dostawców.', '["faktura zakupu","FZ","zakup"]'::jsonb, '["kontrahent_kod -> kontrahenci.kod"]'::jsonb, NULL, 4),
	('faktury_zakupu_pozycje', 'Pozycje faktur zakupu', 'Pozycje dokumentów zakupu.', '[]'::jsonb, '["numer_faktury -> faktury_zakupu.numer_dokumentu","towar_kod -> towary.kod"]'::jsonb, NULL, 5),
	('zamowienia_dostawcy', 'Zamówienia dostawcy', 'Zamówienia złożone u dostawców.', '["zamówienie","ZD","zamówienie do dostawcy"]'::jsonb, '["kontrahent_kod, kod_nadawcy -> kontrahenci.kod"]'::jsonb, NULL, 6),
	('zamowienia_dostawcy_pozycje', 'Pozycje zamówień dostawcy', 'Pozycje zamówień do dostawców.', '[]'::jsonb, '["numer_zamowienia -> zamowienia_dostawcy.numer_dokumentu","towar_kod -> towary.kod"]'::jsonb, NULL, 7),
	('dokumenty_powiazane', 'Dokumenty powiązane', 'Powiązania dokument → dokument.', '[]'::jsonb, '[]'::jsonb, 'Łączy dokumenty na poziomie nagłówków (np. WZ -> FA). Jeden dokument docelowy może mieć wiele źródłowych (np. 3 WZ składają się na 1 FA = trzy wiersze z tym samym numer_docelowy). Brak powiązań na poziomie pojedynczych pozycji.', 8);
--> statement-breakpoint
INSERT INTO "chatbot"."erp_columns" ("table_key", "name", "label", "type", "pk", "searchable", "filterable", "sortable", "position") VALUES
	('kontrahenci', 'kod', 'Kod', 'text', true, true, true, true, 0),
	('kontrahenci', 'nazwa', 'Nazwa', 'text', false, true, true, true, 1),
	('kontrahenci', 'nip', 'NIP', 'text', false, true, true, true, 2),
	('kontrahenci', 'kod_pocztowy', 'Kod pocztowy', 'text', false, true, true, true, 3),
	('kontrahenci', 'miasto', 'Miasto', 'text', false, true, true, true, 4),
	('kontrahenci', 'telefon', 'Telefon', 'text', false, true, true, true, 5),
	('kontrahenci', 'email', 'E-mail', 'text', false, true, true, true, 6),
	('kontrahenci', 'uwagi', 'Uwagi', 'text', false, true, true, false, 7),
	('towary', 'kod', 'Kod', 'text', true, true, true, true, 0),
	('towary', 'nazwa', 'Nazwa', 'text', false, true, true, true, 1),
	('towary', 'ilosc_dostepna', 'Ilość dostępna', 'numeric', false, false, true, true, 2),
	('towary', 'ilosc', 'Ilość', 'numeric', false, false, true, true, 3),
	('towary', 'rezerwacje', 'Rezerwacje', 'numeric', false, false, true, true, 4),
	('towary', 'zamowienia', 'Zamówienia', 'numeric', false, false, true, true, 5),
	('towary', 'cena', 'Cena', 'numeric', false, false, true, true, 6),
	('towary', 'wartosc', 'Wartość', 'numeric', false, false, true, true, 7),
	('towary', 'wartosc_zakupu', 'Wartość zakupu', 'numeric', false, false, true, true, 8),
	('towary', 'jm', 'JM', 'text', false, true, true, true, 9),
	('towary', 'jmp', 'JMP', 'text', false, true, true, true, 10),
	('faktury_sprzedazy', 'numer_dokumentu', 'Numer dokumentu', 'text', true, true, true, true, 0),
	('faktury_sprzedazy', 'status', 'Status', 'text', false, true, true, true, 1),
	('faktury_sprzedazy', 'data_wystawienia', 'Data wystawienia', 'date', false, false, true, true, 2),
	('faktury_sprzedazy', 'kontrahent_kod', 'Kod kontrahenta', 'text', false, true, true, true, 3),
	('faktury_sprzedazy', 'kontrahent_nazwa', 'Kontrahent', 'text', false, true, true, true, 4),
	('faktury_sprzedazy', 'nip', 'NIP', 'text', false, true, true, true, 5),
	('faktury_sprzedazy', 'netto', 'Netto', 'numeric', false, false, true, true, 6),
	('faktury_sprzedazy', 'brutto', 'Brutto', 'numeric', false, false, true, true, 7),
	('faktury_sprzedazy', 'status_ksef', 'Status KSeF', 'text', false, true, true, true, 8),
	('faktury_sprzedazy_pozycje', 'numer_faktury', 'Numer faktury', 'text', true, true, true, true, 0),
	('faktury_sprzedazy_pozycje', 'lp', 'Lp.', 'integer', true, false, true, true, 1),
	('faktury_sprzedazy_pozycje', 'towar_kod', 'Kod towaru', 'text', true, true, true, true, 2),
	('faktury_sprzedazy_pozycje', 'nazwa', 'Nazwa', 'text', false, true, true, true, 3),
	('faktury_sprzedazy_pozycje', 'ilosc', 'Ilość', 'numeric', false, false, true, true, 4),
	('faktury_sprzedazy_pozycje', 'rabat', 'Rabat', 'numeric', false, false, true, true, 5),
	('faktury_sprzedazy_pozycje', 'cena', 'Cena', 'numeric', false, false, true, true, 6),
	('faktury_sprzedazy_pozycje', 'wartosc', 'Wartość', 'numeric', false, false, true, true, 7),
	('faktury_sprzedazy_pozycje', 'marza', 'Marża', 'numeric', false, false, true, true, 8),
	('faktury_zakupu', 'numer_dokumentu', 'Numer dokumentu', 'text', true, true, true, true, 0),
	('faktury_zakupu', 'dokument_zrodlowy', 'Dokument źródłowy', 'text', false, true, true, true, 1),
	('faktury_zakupu', 'status', 'Status', 'text', false, true, true, true, 2),
	('faktury_zakupu', 'data_wplywu', 'Data wpływu', 'date', false, false, true, true, 3),
	('faktury_zakupu', 'data_zakupu', 'Data zakupu', 'date', false, false, true, true, 4),
	('faktury_zakupu', 'kontrahent_kod', 'Kod kontrahenta', 'text', false, true, true, true, 5),
	('faktury_zakupu', 'kontrahent_nazwa', 'Kontrahent', 'text', false, true, true, true, 6),
	('faktury_zakupu', 'nip', 'NIP', 'text', false, true, true, true, 7),
	('faktury_zakupu', 'miasto', 'Miasto', 'text', false, true, true, true, 8),
	('faktury_zakupu', 'netto', 'Netto', 'numeric', false, false, true, true, 9),
	('faktury_zakupu', 'brutto', 'Brutto', 'numeric', false, false, true, true, 10),
	('faktury_zakupu_pozycje', 'numer_faktury', 'Numer faktury', 'text', true, true, true, true, 0),
	('faktury_zakupu_pozycje', 'lp', 'Lp.', 'integer', true, false, true, true, 1),
	('faktury_zakupu_pozycje', 'towar_kod', 'Kod towaru', 'text', true, true, true, true, 2),
	('faktury_zakupu_pozycje', 'nazwa', 'Nazwa', 'text', false, true, true, true, 3),
	('faktury_zakupu_pozycje', 'ilosc', 'Ilość', 'numeric', false, false, true, true, 4),
	('faktury_zakupu_pozycje', 'jm', 'JM', 'text', false, true, true, true, 5),
	('faktury_zakupu_pozycje', 'cena', 'Cena', 'numeric', false, false, true, true, 6),
	('faktury_zakupu_pozycje', 'wartosc', 'Wartość', 'numeric', false, false, true, true, 7),
	('zamowienia_dostawcy', 'numer_dokumentu', 'Numer dokumentu', 'text', true, true, true, true, 0),
	('zamowienia_dostawcy', 'status', 'Status', 'text', false, true, true, true, 1),
	('zamowienia_dostawcy', 'termin_dostawy', 'Termin dostawy', 'date', false, false, true, true, 2),
	('zamowienia_dostawcy', 'kontrahent_kod', 'Kod kontrahenta', 'text', false, true, true, true, 3),
	('zamowienia_dostawcy', 'kontrahent_nazwa', 'Kontrahent', 'text', false, true, true, true, 4),
	('zamowienia_dostawcy', 'nip', 'NIP', 'text', false, true, true, true, 5),
	('zamowienia_dostawcy', 'miasto', 'Miasto', 'text', false, true, true, true, 6),
	('zamowienia_dostawcy', 'nadawca', 'Nadawca', 'text', false, true, true, true, 7),
	('zamowienia_dostawcy', 'kod_nadawcy', 'Kod nadawcy', 'text', false, true, true, true, 8),
	('zamowienia_dostawcy', 'netto', 'Netto', 'numeric', false, false, true, true, 9),
	('zamowienia_dostawcy', 'brutto', 'Brutto', 'numeric', false, false, true, true, 10),
	('zamowienia_dostawcy_pozycje', 'numer_zamowienia', 'Numer zamówienia', 'text', true, true, true, true, 0),
	('zamowienia_dostawcy_pozycje', 'lp', 'Lp.', 'integer', true, false, true, true, 1),
	('zamowienia_dostawcy_pozycje', 'towar_kod', 'Kod towaru', 'text', true, true, true, true, 2),
	('zamowienia_dostawcy_pozycje', 'nazwa', 'Nazwa', 'text', false, true, true, true, 3),
	('zamowienia_dostawcy_pozycje', 'ilosc', 'Ilość', 'numeric', false, false, true, true, 4),
	('zamowienia_dostawcy_pozycje', 'jm', 'JM', 'text', false, true, true, true, 5),
	('zamowienia_dostawcy_pozycje', 'cena', 'Cena', 'numeric', false, false, true, true, 6),
	('zamowienia_dostawcy_pozycje', 'wartosc', 'Wartość', 'numeric', false, false, true, true, 7),
	('dokumenty_powiazane', 'numer_zrodlowy', 'Numer źródłowy', 'text', true, true, true, true, 0),
	('dokumenty_powiazane', 'typ_zrodlowy', 'Typ źródłowy', 'text', false, true, true, true, 1),
	('dokumenty_powiazane', 'numer_docelowy', 'Numer docelowy', 'text', true, true, true, true, 2),
	('dokumenty_powiazane', 'typ_docelowy', 'Typ docelowy', 'text', false, true, true, true, 3),
	('dokumenty_powiazane', 'data', 'Data', 'date', false, false, true, true, 4);
